#!/bin/bash

exec 6>&-
exec 6<&-

while ! exec 6<>/dev/tcp/redis/6379; do
    echo "$(date) - still trying to connect to redis at ${TESTING_REDIS_URL}"
    sleep 1
done

exec 6>&-
exec 6<&-

until $(curl --output /dev/null --silent --fail "http://elasticsearch:9200/_cluster/health?wait_for_status=green&timeout=10s"); do
    sleep 1
done

exec 6>&-
exec 6<&-

cd /var/www/apisearch && composer test